intuit/config/routes.rb
Rails.application.routes.draw do
  get 'companies/create'

  get 'companies/authenticate'

  get 'companies/logout'

  get 'companies/oauth_callback'

  resources :vendors

  root to: 'companies#index'

  resources :companies do 
    collection do 
      get :authenticate, defaults: { format: 'json' }
      post :report_ranged, defaults: { format: 'json' }
      get :oauth_callback
      get :logout
      get :xero_create
      get :xero_new

    end
  end

  get '/companies/blue-dot' => 'companies#bluedot'

end

intuit/app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

intuit/app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    vendor = Quickbooks::Model::Vendor.new 
    vendor.given_name = vendor_params[:name]
    vendor.email_address = vendor_params[:email_address]
    @vendor_service.create(vendor)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    Quickbooks.logger = Rails.logger 
    Quickbooks.log = true 

    respond_to do |format|
      if @vendor.update(vendor_params)
        #this line checkts over the vendor service, checking all entriies. where is @vendor_service readily available though?
        vendor = @vendor_service.query("SELECT * FROM VENDOR WHERE GivenName = '#{vendor_params[:name]}'").entries.first

        vendor.email_address = vendor_params[:email_address]

        @vendor_service.update(vendor)

        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name, :email_address)
    end
end

intuit/app/helpers/vendors_helper.rb
module VendorsHelper
end

intuit/app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.email_field :email_address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

intuit/app/views/vendors/edit.html.erb
<h1>Editing vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

intuit/app/views/vendors/index.html.erb
<h1>Listing vendors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email address</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
      ... omitted
        <td><%= vendor.email_address %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

intuit/app/views/vendors/new.html.erb
<h1>New vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

intuit/app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<p>
  <strong>email_address:</strong>
  <%= @vendor.email_address %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>