intuit/config/routes.rb
Rails.application.routes.draw do
  get 'companies/create'

  get 'companies/authenticate'

  get 'companies/logout'

  get 'companies/oauth_callback'

  resources :vendors

  root to: 'companies#index'

  resources :companies do 
    collection do 
      get :authenticate, defaults: { format: 'json' }
      post :report_ranged, defaults: { format: 'json' }
      get :oauth_callback
      get :logout
      get :xero_create
      get :xero_new

    end
  end

  get '/companies/blue-dot' => 'companies#bluedot'

end

intuit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Intuit</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if !session[:token] %>
      <div class="connect-intuit">
        <ipp:connectToIntuit></ipp:connectToIntuit>
      </div>

      <%= link_to "Sign in via Xero", xero_new_companies_path %>
    <% else %>
      <p> Logout here: </p> <br>
      Company Name: <%= current_company.name %> <br>
      <%= link_to "Logout", companies_logout_path %>
      
    <% end %>

    <% if notice %>
      <div style="padding: 10px;background: gainsboro;font-weight: 900;width: 50%;"><%= notice %></div>
    <% end %>

    <%= yield %>

    <script  type="text/javascript"
     src="https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere-1.3.0.js"></script>

    <script>
        intuit.ipp.anywhere.setup({menuProxy: '<%= companies_blue_dot_url %>', grantUrl: '<%= authenticate_companies_url %>'});
    </script>
  </body>
</html>